name: biliran_creative_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Default
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  firebase_messaging: any

  # Social Auth  
  flutter_facebook_auth: ^7.1.0
  sign_in_with_apple: ^6.1.0
  
  # State Management
  provider: any

  # UI & Utils
  image_picker: any
  table_calendar: any
  intl: any
  flutter_local_notifications: any
  google_sign_in: any
  smooth_page_indicator: ^1.2.0+2  
  curved_navigation_bar: ^1.0.3 # ✅ Needed for WormEffect

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Make sure this folder exists in your project root
  assets:
    - assets/
