name: biliran_creative_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    


  # Default
  cupertino_icons: ^1.0.8

  # for country code picker
  intl_phone_field: ^3.2.0

  # Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2 # for Firestore
  firebase_storage: any
  firebase_messaging: any
  firebase_auth: ^6.1.0    # for Authentication
  firebase_database: ^12.0.2  # if using Realtime Database

  # Social Auth  
  flutter_facebook_auth: ^7.1.0
  sign_in_with_apple: ^7.0.1
  
  # State Management
  provider: any

  # UI & Utils
  image_picker: any
  table_calendar: any
  intl: any
  flutter_local_notifications: any
  google_sign_in: 6.2.1
  smooth_page_indicator: ^1.2.0+2  
  curved_navigation_bar: ^1.0.3 # ✅ Needed for WormEffect

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ✅ Make sure this folder exists in your project root
  assets:
    - packages/intl_phone_field/assets/flags/
