# Project-wide Gradle settings

# Increase memory for Gradle builds (important for Flutter projects)
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Enable AndroidX (required for modern Flutter versions)
android.useAndroidX=true
android.enableJetifier=true

# Force Gradle to use this specific NDK version
# Make sure you have this folder:
# C:\Users\Admin\AppData\Local\Android\Sdk\ndk\25.2.9519653
android.ndkVersion=25.2.9519653

# Force Gradle to use JDK 17 instead of JDK 24
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.16.8-hotspot
