// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjRk0I4EQOsHHldewn1NxP6KJs5wEFklA',
    appId: '1:817740614273:web:797c9b56a52d2e2c191b80',
    messagingSenderId: '817740614273',
    projectId: 'bilirancreativeapp',
    authDomain: 'bilirancreativeapp.firebaseapp.com',
    storageBucket: 'bilirancreativeapp.firebasestorage.app',
    measurementId: 'G-36Z08RG2HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd3oNZVMKvg9SSKe-Lxf2IJ6XoTUCJgEU',
    appId: '1:817740614273:android:b28c6d364bd10211191b80',
    messagingSenderId: '817740614273',
    projectId: 'bilirancreativeapp',
    storageBucket: 'bilirancreativeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpi1ddWwZGHAA89Sb4WfN9-bQwG7BsMhg',
    appId: '1:817740614273:ios:3a3304308c5ccb31191b80',
    messagingSenderId: '817740614273',
    projectId: 'bilirancreativeapp',
    storageBucket: 'bilirancreativeapp.firebasestorage.app',
    iosBundleId: 'com.example.biliranCreativeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpi1ddWwZGHAA89Sb4WfN9-bQwG7BsMhg',
    appId: '1:817740614273:ios:3a3304308c5ccb31191b80',
    messagingSenderId: '817740614273',
    projectId: 'bilirancreativeapp',
    storageBucket: 'bilirancreativeapp.firebasestorage.app',
    iosBundleId: 'com.example.biliranCreativeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjRk0I4EQOsHHldewn1NxP6KJs5wEFklA',
    appId: '1:817740614273:web:e4c963d235bf2999191b80',
    messagingSenderId: '817740614273',
    projectId: 'bilirancreativeapp',
    authDomain: 'bilirancreativeapp.firebaseapp.com',
    storageBucket: 'bilirancreativeapp.firebasestorage.app',
    measurementId: 'G-J2KPF1N7H7',
  );
}
