import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'core/theme.dart';
import 'screens/role_selection_page.dart';
import 'screens/client/client_home.dart';
import 'screens/creative/creative_home.dart';
import 'screens/admin/admin_dashboard.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Creative Booking App',
      theme: AppTheme.light,
      debugShowCheckedModeBanner: false,
      home: const AuthWrapper(),
      routes: {
        '/role_selection': (_) => const RoleSelectionPage(),
        '/client_home': (_) => const ClientHomePage(),   // ✅ Fixed class name
        '/creative_home': (_) => const CreativeHomePage(), // ✅ Fixed class name
        '/admin_dashboard': (_) => const AdminDashboardPage(), // ✅ Fixed class name
      },
    );
  }
}

/// AuthWrapper decides which screen to show:
/// 1. Not logged in → show RoleSelectionPage → navigate to AuthPage
/// 2. Logged in → fetch role and redirect to respective home page
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // User not logged in
        if (!snapshot.hasData) return const RoleSelectionPage();

        final uid = snapshot.data!.uid;

        // Fetch user document to get role
        return FutureBuilder<DocumentSnapshot>(
          future: FirebaseFirestore.instance.collection('users').doc(uid).get(),
          builder: (context, userSnapshot) {
            if (userSnapshot.connectionState == ConnectionState.waiting) {
              return const Scaffold(
                body: Center(child: CircularProgressIndicator()),
              );
            }

            if (!userSnapshot.hasData || !userSnapshot.data!.exists) {
              return const RoleSelectionPage(); // fallback if user doc not found
            }

            final userData =
                userSnapshot.data!.data() as Map<String, dynamic>;
            final role = userData['role'];

            // Redirect based on role
            if (role == 'client') return const ClientHomePage();
            if (role == 'creative') return const CreativeHomePage();
            if (role == 'admin') return const AdminDashboardPage();

            // Fallback
            return const RoleSelectionPage();
          },
        );
      },
    );
  }
}
