import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'core/theme.dart';
import 'screens/role_selection_page.dart';
import 'screens/client/client_home_page.dart';
import 'screens/creative/creative_home.dart';
import 'screens/admin/admin_dashboard.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
// Add this

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Upload categories once
  
  

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Creative Booking App',
      theme: AppTheme.light,
      debugShowCheckedModeBanner: false,
      home: const AuthWrapper(),
      routes: {
        '/role_selection': (_) => const RoleSelectionPage(),
        '/client_home': (_) => const ClientHomePage(clientName: '',),
        '/creative_home': (_) => const CreativeHomePage(),
        '/admin_dashboard': (_) => const AdminDashboardPage(),
      },
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return const RoleSelectionPage();

        final uid = snapshot.data!.uid;

        return FutureBuilder<DocumentSnapshot>(
          future: FirebaseFirestore.instance.collection('users').doc(uid).get(),
          builder: (context, userSnapshot) {
            if (userSnapshot.connectionState == ConnectionState.waiting) {
              return const Scaffold(
                body: Center(child: CircularProgressIndicator()),
              );
            }

            if (!userSnapshot.hasData || !userSnapshot.data!.exists) {
              return const RoleSelectionPage();
            }

            final userData = userSnapshot.data!.data() as Map<String, dynamic>;
            final role = userData['role'];

            if (role == 'client') return const ClientHomePage(clientName: '',);
            if (role == 'creative') return const CreativeHomePage();
            if (role == 'admin') return const AdminDashboardPage();

            return const RoleSelectionPage();
          },
        );
      },
    );
  }
}
